routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::resource('item','ItemController');
Route::delete('/item/trash/{item}', 'ItemController@trash')->name('item.trash');

app/Item.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Item extends Model
{
    use SoftDeletes;

    protected $dates = ['deleted_at'];
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/ItemController.php
<?php

namespace App\Http\Controllers;

use App\Item;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Input;
use App\Http\Requests\StoreItemRequest;
use App\Http\Requests\EditItemRequest;

class ItemController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {

        $search = Input::get('search');

        if (filled($search)) {
            $items = Item::where('name', $search)->latest()->paginate(6);
        }
        else {
            $items = Item::latest()->paginate(6);
        }

        return view('item.index', compact('items','search'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('item.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreItemRequest $request)
    {
        $item = new Item;

        $item->name=$request->name;
        $item->description=$request->description;
        $item->category=$request->category;
        $item->material=$request->material;
        if($request->has('available')) {
            $item->available=$request->available;
        }else{
            $item->available= 0;
        }
        $item->save();

        return redirect()->route('item.index')->with('success','create success');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Item  $item
     * @return \Illuminate\Http\Response
     */
    public function show(Item $item)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Item  $item
     * @return \Illuminate\Http\Response
     */
    public function edit(Item $item)
    {
        return view('item.edit',compact('item'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Item  $item
     * @return \Illuminate\Http\Response
     */
    public function update(EditItemRequest $request, Item $item)
    {
        $item->name=$request->name;
        $item->description=$request->description;
        $item->category=$request->category;
        $item->material=$request->material;
        if($request->has('available')) {
            $item->available=$request->available;
        }else{
            $item->available= 0;
        }
        $item->save();

        return redirect()->route('item.index')->with('message','update success');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Item  $item
     * @return \Illuminate\Http\Response
     */
    public function destroy(Item $item)
    {
        $item->forceDelete();
        return redirect()->route('item.index')->with('message','delete success');
    }

    public function trash(Item $item)
    {
        $item->delete();
        return redirect()->route('item.index')->with('message','trash success');
    }
}

resources/views/item/create.blade.php
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
    <head>
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1">

      <title>Item</title>

      <link href="https://fonts.googleapis.com/css?family=Nunito:200,600" rel="stylesheet">
      <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
      
      <style>
          html, body {
            background-color: #fff;
            color: #636b6f;
            font-family: 'Nunito', sans-serif;
            font-weight: 200;
            height: 100vh;
            margin: 0;
          }

          .full-height {
            height: 100vh;
          }

          .flex-center {
            align-items: center;
            display: flex;
            justify-content: center;
          }

          .content {
            text-align: center;
          }
      </style>
    </head>
    <body>
    <div class="flex-center position-ref full-height">
      <div class="container">
        <div>
          <a href="{{ route('item.index') }}" class="btn btn-secondary btn-lg active" role="button" aria-pressed="true">go back</a>
        </div>
        <br>
        <form action="{{ route('item.store') }}" method="POST">
            @csrf
            @if($errors->any())
                @foreach($errors->all() as $error)
                  <div class="alert alert-danger">
                    {{ $error }}
                  </div>
                @endforeach
            @endif
            <div class="form-group">
              <label for="name">Item name</label>
              <input type="text" name="name" id="name" class="form-control" value="{{ old('name') }}">
            </div>
            <div class="form-group">
                  <label for="description"> description</label>
                  <textarea name="description" id="description" class="form-control">{{ old('description') }}</textarea>
            </div>
            <div class="form-group">
                  <label for="category"> category</label>
                  <select name="category" class="form-control">
                    <option value="category1" {{ (old("category") == 'category1' ? "selected":"") }}> category 1 </option>
                    <option value="category2" {{ (old("category") == 'category2' ? "selected":"") }}> category 2 </option>
                  </select>
            </div>
            <div class="form-group">
              <label for="material"> material</label><br>
                <input type="radio" name="material" value="glass" @if(old('material') == 'glass') checked="checked" @endif > glass<br>
                <input type="radio" name="material" value="metal" @if(old('material') == 'metal') checked="checked" @endif > metal<br>  
                <input type="radio" name="material" value="plastic" @if(old('material') == 'plastic') checked="checked" @endif > plastic<br> 
            </div>
            <div class="form-check">
              <input type="checkbox"  name="available" class="form-check-input" value="1" id="available" @if(old('available')) checked @endif>
              <label class="form-check-label" for="available"  >available</label>
            </div>
            <br>
            <button type="submit" class="btn btn-primary">Create</button>
        </form>    
      </div>  
      </div>
    </body>
</html>

resources/views/item/edit.blade.php
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
    <head>
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1">

      <title>Item</title>

      <link href="https://fonts.googleapis.com/css?family=Nunito:200,600" rel="stylesheet">
      <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
      
      <style>
          html, body {
            background-color: #fff;
            color: #636b6f;
            font-family: 'Nunito', sans-serif;
            font-weight: 200;
            height: 100vh;
            margin: 0;
          }

          .full-height {
            height: 100vh;
          }

          .flex-center {
            align-items: center;
            display: flex;
            justify-content: center;
          }

          .content {
            text-align: center;
          }
      </style>
    </head>
    <body>
    <div class="flex-center position-ref full-height">
      <div class="container">
        <div>
        <a href="{{ route('item.index') }}" class="btn btn-secondary btn-lg active" role="button" aria-pressed="true">go back</a>
        </div>
        <br>
        <form action="{{ route('item.update' , $item->id) }}" method="POST">
            @csrf
            @method('PUT')

            @if($errors->any())
                @foreach($errors->all() as $error)
                  <div class="alert alert-danger">
                    {{ $error }}
                  </div>
                @endforeach
            @endif
            <div class="form-group">
              <label for="name">Item name</label>
              <input type="text" name="name" id="name" class="form-control" value="{{ old('name', $item->name) }}">
            </div>
            <div class="form-group">
                  <label for="description"> description</label>
                  <textarea name="description" id="description" class="form-control">{{ old('description', $item->description) }}</textarea>
            </div>
            <div class="form-group">
                  <label for="category"> category</label>
                  <select name="category" class="form-control">
                    <option value="category1" {{ (old('category', $item->category) == 'category1' ? 'selected' : '') }}> category 1 </option>
                    <option value="category2" {{ (old('category', $item->category) == 'category2' ? 'selected' : '') }}> category 2 </option>
                  </select>
            </div>
            <div class="form-group">
              <label for="material"> material</label><br>
                <input type="radio" name="material" value="glass" {{ old('material', $item->material )== "glass" ? 'checked' : '' }} > glass<br>
                <input type="radio" name="material" value="metal" {{ old('material', $item->material )== "metal" ? 'checked' : '' }} > metal<br>  
                <input type="radio" name="material" value="plastic" {{ old('material', $item->material )== "plastic" ? 'checked' : '' }} > plastic<br> 
            </div>
            <div class="form-check">
              <input type="checkbox"  name="available" class="form-check-input" value="1" id="available" @if(old('available', $item->available)) checked @endif>
              <label class="form-check-label" for="available"  >available</label>
            </div>
            <br>
            <button type="submit" class="btn btn-primary">Edit</button>
        </form>    
      </div>  
      </div>
    </body>
</html>

resources/views/item/index.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <title>Laravel</title>

        <!-- Fonts -->
        <link href="https://fonts.googleapis.com/css?family=Nunito:200,600" rel="stylesheet">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

        <!-- Styles -->
        <style>
            html, body {
                background-color: #fff;
                color: #636b6f;
                font-family: 'Nunito', sans-serif;
                font-weight: 200;
                height: 100vh;
                margin: 0;
            }

            .full-height {
                height: 100vh;
            }

            .flex-center {
                padding-top: 100px;
                display: flex;
                justify-content: center;
            }

            .content {
                text-align: center;
            }


            
        </style>
    </head>
    <body>
        <div class="flex-center position-ref full-height">
            <div class="content">
                <div class="container">
                    <a href="{{ route('item.create') }}" class="btn btn-secondary btn-lg active" role="button" aria-pressed="true">Create Item</a>
                </div>
                <div class="container-fluid">
                <br><br>
                @if(session()->has('message'))
                    <div class="alert alert-success">
                        {{ session()->get('message') }}
                    </div>
                @endif
                <form action="" method="GET" class="form-inline">
                    <input class="form-control" placeholder="name" type="text" name="search" value="{{ $search }}">
                    <input class="btn btn-primary" type="submit" value="search">
                </form>
                <br>
                <table id="selectedColumn" class="table table-striped table-bordered table-sm" cellspacing="0" width="100%">
                    <thead>
                        <tr>
                            <th class="th-sm">Name </th>
                            <th class="th-sm">description </th>
                            <th class="th-sm">material </th>
                            <th class="th-sm">category </th>
                            <th class="th-sm">available</th>
                            <th class="th-sm">edit</th>
                            <th class="th-sm">trash</th>
                            <th class="th-sm">delete</th>
                        </tr>
                    </thead>
                    <tbody>
                    @foreach($items as $item)
                        <tr>
                            <td>{{ $item->name }}</td>
                            <td>{{ $item->description }}</td>
                            <td>{{ $item->material }}</td>
                            <td>{{ $item->category }}</td>
                            <td>{{ $item->available == 1 ? "yes" : "no" }}</td>
                            <td><a class="btn btn-info" href="{{ route('item.edit', $item->id) }}" role="button">edit</a></td>
                            <td>
                                <form method="POST" action="{{ route('item.trash', $item->id) }}">
                                        @csrf
                                        @method('DELETE')
                                        <div class="form-group">
                                            <input type="submit" class="btn btn-warning" value="Trash">
                                        </div>
                                    </form>
                            </td>
                            <td>  
                                <form method="POST" action="{{ route('item.destroy', $item->id) }}">
                                    @csrf
                                    @method('DELETE')
                                    <div class="form-group">
                                        <input type="submit" class="btn btn-danger" value="Delete">
                                    </div>
                                </form>     
                            </td>
                        </tr>
                    @endforeach    
                    </tbody>
                </table>
            </div>
        {{ $items->links() }}
        </div>
    </body>
</html>